#!/usr/bin/env bash

# see https://sharats.me/posts/shell-script-best-practices/ for source
# and inspiration
#
set -o errexit
set -o nounset
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

###
### prepfork - prepare dist-git fork
###
###    Prepares dist-git package fork for update
###    and PR
###
### Usage:
###   prepfork               -- this help file
###   prepfork -h            -- this help file
###   prepfork -y            -- execute without git clean
###   prepfork -Y            -- execute with git clean
###   prepfork <option>      -- execute with options
###
### Options:
###  <option>    Some option to process
###  -y          Execute script without using git clean
###  -Y          Execute  script with git clean
###  -h          Show this message
###

# See: https://gist.github.com/kovetskiy/a4bb510595b3a6b17bfd1bd9ac8bb4a5
help() {
  sed -rn 's/^### ?//;T;p' "$0"
}

# check for -h or zero arguements
# if [[ $# == 0 || "$1" == "-h" ]]; then
if [[ $# == 0 || "${1-}" =~ ^-*h(elp)?$ ]]; then
  help
  exit 1
fi

# main
main () {
  # check for -y
  if [[ "${1-}" =~ (y|Y) ]]; then
    echo "*** Option: ${1}"
    printf "** Preparing fork for PR\n"

    if [[ "${1-}" == "-Y" ]]; then
      echo "*** git clean"
      git clean -fxd -e newrelease.conf
    fi

    echo "*** checkout rawhide"
    git co rawhide

    echo "** git fetch"
    git fetch -v

    echo "** merge origin/rawhide"
    git merge origin/rawhide

    # echo "** fetch upstream"
    # git fetch upstream

    echo "** merge upstream"
    git merge upstream/rawhide

    echo "** push to origin"
    git push origin rawhide

    echo "** current branches"
    git branch -v

    printf "**** Create branch for new version\n\n"
  else
    echo "Execute flag not set. Process option and proceed"
  fi

  echo "** main done **"
}

main "$@"

echo "** script done **"
