#!/usr/bin/env bash

# see https://sharats.me/posts/shell-script-best-practices/ for source
# and inspiration
#
set -o errexit
set -o nounset
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

# constants
COUNT=1
WAIT=2

# userset repo
REPO=/home/bgsmith/src/userset-dotfiles/src

###
### userset - scp essential dotfiles to target
###
###    Copies select dotfiles to target fedora machine.
###    Use dns name or ip to identify target.
###    Also installs key dependencies.
###    Assumes basic user account already on machine and ssh key.
###
### Usage:
###   userset               -- this help file
###   userset -c            -- copy files to repo
###   userset -h            -- this help file
###   userset -y target     -- execute
###
### Options:
###  -y          Execute script
###  -h          Show this message
###  -c          Copy config files to REPO
###
### Argument:
###  target      Target machine name/ip

# See: https://gist.github.com/kovetskiy/a4bb510595b3a6b17bfd1bd9ac8bb4a5
help() {
  sed -rn 's/^### ?//;T;p' "$0"
}

# check for -h or zero arguments
# if [[ $# == 0 || "$1" == "-h" ]]; then
if [[ $# == 0 || "${1-}" =~ ^-*h(elp)?$ ]]; then
  help
  exit 1
fi

# main
main () {
  goflag="false"
  while getopts 'chy' OPTION
  do
      case $OPTION in
          c) cp ~/.bashrc $REPO
             mkdir -p $REPO/.bashrc.d
             cp -r ~/.bashrc.d/* $REPO/.bashrc.d/
             mkdir -p $REPO/.config/tmux
             cp ~/.config/tmux/tmux* $REPO/.config/tmux/
             mkdir -p $REPO/.config/tmux/plugins/tpm
             cp -a ~/.config/tmux/plugins/tpm/* $REPO/.config/tmux/plugins/tpm/
             mkdir -p $REPO/.config/vim
             cp -a ~/.config/vim/vimrc $REPO/.config/vim/
             mkdir -p $REPO/.config/vim/pack/minpac/opt/minpac
             cp -a ~/.config/vim/pack/minpac/opt/minpac/* $REPO/.config/vim/pack/minpac/opt/minpac/
             mkdir -p $REPO/.config
             cp ~/.config/starship.toml $REPO/.config
             echo "Copy done"
             pushd $REPO
             if [ -n "$(git status --porcelain)" ]; then
i              git add *
               NOW=$(date +%Y-%m-%d_%T)
               git commit -m "Update repo - $NOW"
               git push origin
               echo "Git done"
             fi
             popd
             exit 0
             ;;
          h) help
             exit 0
             ;;
          y) goflag="true"
             ;;
          ?) printf "Usage: sudo %s [-c] [-h] [-y] target\n" ${0##*/} >&2
             exit 2
             ;;
      esac
  done
  shift $(($OPTIND - 1))

  # check target is not empty
  if [[ $# -eq 0 ]] ; then
    echo -e "/nTarget missing"
    help
    exit 1
  fi

  # Handle remaining positional arguments
  target=("$1")

  # process dry run if toggled
  if ! "$goflag" ; then
    echo -e "\nDry run"
    echo "  - Target: $target"
    exit 0
  fi

  # check that target is valid and online
  pingmsg="\n$target is"
  if ping -c $COUNT -W $WAIT $target >/dev/null 2>&1; then
    echo -e "$pingmsg up"
  else
    echo -e "$pingmsg not available"
    exit 1
  fi

  # bashrc
  echo " - bashrc"
  scp -p ~/.bashrc $target:~/.bashrc

  # bashrc.d
  echo " - bashrc.d"
  dirstr=~/.bashrc.d
  ssh $target "mkdir -p $dirstr" && scp -p $dirstr/* $target:$dirstr/

  # vim, including minpac but not plugsins
  echo " - vim and minpack"
  dirstr=~/.config/vim
  ssh $target "mkdir -p $dirstr" && scp -p $dirstr/vimrc $target:$dirstr/vimrc
  dirstr=~/.config/vim/pack/minpac/opt/minpac/
  ssh $target "mkdir -p $dirstr" && scp -r -p $dirstr/* $target:$dirstr/

  # starship
  echo " - starship.toml"
  dirstr=~/.config
  ssh $target "mkdir -p $dirstr" && scp -p $dirstr/starship.toml $target:$dirstr/

  # tmux and tpm 
  echo " - tmux"
  dirstr=~/.config/tmux
  ssh $target "mkdir -p $dirstr" && scp -p $dirstr/tmux.* $target:$dirstr/
  dirstr=~/.config/tmux/plugins/tmp
  ssh $target "mkdir -p $dirstr" && scp -r -p $dirstr/* $target:$dirstr/
}

main "$@"

